# this config file contains all config fields with comments
# NOTE: this is not a particularly useful config file
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  apiServerAddress: "172.18.0.1"
  #serviceSubnet: "172.18.0.0/16"
  podSubnet: "10.244.0.0/16"
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration
  evictionHard:
    nodefs.available: "0%"
# patch it further using a JSON 6902 patch
kubeadmConfigPatchesJSON6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: my-hostname
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://openmcp:5000"]
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  image: kindest/node:v1.17.5@sha256:ab3f9e6ec5ad8840eeb1f76c89bb7948c77bbf76bcebe1a8b59790b8ae9a283a
  extraMounts:
  - hostPath: /opt/cni/bin
    containerPath: /opt/cni/bin

# the three workers
- role: worker
  image: kindest/node:v1.17.5@sha256:ab3f9e6ec5ad8840eeb1f76c89bb7948c77bbf76bcebe1a8b59790b8ae9a283a
  extraPortMappings:
  - containerPort: 30000 # API SERVER NodePort
    hostPort: 30000
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30001 # Analytic Engine NodePort
    hostPort: 30001
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30002 # MetricCollector NodePort
    hostPort: 30002
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30003 # InfluxDB NodePort
    hostPort: 30003
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30004 # LoadBalancer NodePort
    hostPort: 30004
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30350 # Kiali NodePort
    hostPort: 30350
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30901 # Postgresql NodePort
    hostPort: 30901
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30902 # Portal API NodePort
    hostPort: 30902
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30903 # Portal Web NodePort
    hostPort: 30903
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  extraMounts:
  - hostPath: /home/cluster01/data
    containerPath: /mnt
  - hostPath: /home/cluster01/.kube
    containerPath: /kube
  - hostPath: /home/cluster01/.init
    containerPath: /init
  - hostPath: /home/nfs/pv/api-server/cert #/home/cluster01/apicert
    containerPath: /cert
  - hostPath: /usr/share/zoneinfo/Asia/Seoul
    containerPath: /usr/share/zoneinfo/Asia/Seoul
  - hostPath: /opt/cni/bin
    containerPath: /opt/cni/bin

